### ISSUE TITLE
test_report_tenplate.html

### ISSUE THREAD

**Issue by patrikarlos** [telefonicaid/fiware-health#14]
When running the fiware-region-sanity-tests, the timestamp variable in test_report_template.html does not replace with the timestamp correctly. The resulting html file is empty where the timestamp is to be found. 
Output is; (tests_results.html) (adapted to not mess with html formatting too much)
...[snip]..
h1 FIWARE REGIONS - SANITY CHECK | /h1
...[snip]..

**Comment by flopezag** [comment]
Hi @patrikarlos 

Are you running locally the validation test?

**Comment by jframos** [comment]
Hi @patrikarlos,

Could you please check if the _nose-html-reporting_ lib you are using is the one detailed in the [requirements file](https://github.com/telefonicaid/fiware-health/blob/develop/fiware-region-sanity-tests/requirements.txt)? (downloaded from [telefonicaid/nose-html-reporting](https://github.com/telefonicaid/nose-html-reporting) repository instead of the PyPI repository)

That library includes some improvements to manage the timestamp in reports.

To make sure you have installed the correct lib, please uninstall it (_pip uninstall nose-html-reporting_) and install the provided requirements in the project (_pip install -r requirements.txt --allow-all-external_)

**Comment by patrikarlos** [comment]
Hej!
@flopezag , yes we are running from our monitor. We saw that we had some errors, and wanted to see if we could trace down the issue. So we run the tests once every hour. Will prevent it from running when your's running. We accidentally ran it from two different hosts, and got lots of 'ERROR's, network overlap etc. AFAIK, this is due to Grizzly and bad IP namespace handling. 

@jframos I've cloned it from the github, and followed it's instructions. Perhaps, something got mixed up. Perhaps, you can include the '(pip install -r requirements.txt --allow-all-external)' in the read me file, for the fiware-region-sanity-checks.  (Testing now).

Worked perfectly, used the incorrect library. Could you add a test, as to point it out to the user?
