### ISSUE TITLE
Please remove Berlin from sanity-check

### ISSUE THREAD

**Issue by tgu-git** [telefonicaid/fiware-health#93]
Berlin was the old Grizzly setup and is not used anymore. Therefore it can be removed from the list of nodes to check the health.

**Comment by flopezag** [comment]
This is not part of the Health, Berlin is deleted from the test and from the jobs in Jenkins but it stays in the Context Broker. This mean mainly that it does not receive any monitoring data from Berlin2 yet. This is something to be discussed, due to the scenario of deleting a node in the Context Broker is not discussed previously and affect both Health, Infographics and Federation Monitoring.
